Upgrade Capybara
Was getting an error: `undefined method `stdio' for
Puma::Events:Class`. This is because of an incompatibility between
capybara and puma 6. Updating capybara fixes the issue:

https://github.com/teamcapybara/capybara/issues/2605